/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the TimeZoneDetailedXMLResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeZoneDetailedXMLResponse{}

// TimeZoneDetailedXMLResponse struct for TimeZoneDetailedXMLResponse
type TimeZoneDetailedXMLResponse struct {
	Ip *string `json:"ip,omitempty"`
	AirportDetails *TimezoneAirport `json:"airport_details,omitempty"`
	LoCodeDetails *TimezoneLocode `json:"lo_code_details,omitempty"`
	Location *TimezoneLocation `json:"location,omitempty"`
	TimeZone *TimezoneDetail `json:"time_zone,omitempty"`
}

// NewTimeZoneDetailedXMLResponse instantiates a new TimeZoneDetailedXMLResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeZoneDetailedXMLResponse() *TimeZoneDetailedXMLResponse {
	this := TimeZoneDetailedXMLResponse{}
	return &this
}

// NewTimeZoneDetailedXMLResponseWithDefaults instantiates a new TimeZoneDetailedXMLResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeZoneDetailedXMLResponseWithDefaults() *TimeZoneDetailedXMLResponse {
	this := TimeZoneDetailedXMLResponse{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *TimeZoneDetailedXMLResponse) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeZoneDetailedXMLResponse) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *TimeZoneDetailedXMLResponse) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *TimeZoneDetailedXMLResponse) SetIp(v string) {
	o.Ip = &v
}

// GetAirportDetails returns the AirportDetails field value if set, zero value otherwise.
func (o *TimeZoneDetailedXMLResponse) GetAirportDetails() TimezoneAirport {
	if o == nil || IsNil(o.AirportDetails) {
		var ret TimezoneAirport
		return ret
	}
	return *o.AirportDetails
}

// GetAirportDetailsOk returns a tuple with the AirportDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeZoneDetailedXMLResponse) GetAirportDetailsOk() (*TimezoneAirport, bool) {
	if o == nil || IsNil(o.AirportDetails) {
		return nil, false
	}
	return o.AirportDetails, true
}

// HasAirportDetails returns a boolean if a field has been set.
func (o *TimeZoneDetailedXMLResponse) HasAirportDetails() bool {
	if o != nil && !IsNil(o.AirportDetails) {
		return true
	}

	return false
}

// SetAirportDetails gets a reference to the given TimezoneAirport and assigns it to the AirportDetails field.
func (o *TimeZoneDetailedXMLResponse) SetAirportDetails(v TimezoneAirport) {
	o.AirportDetails = &v
}

// GetLoCodeDetails returns the LoCodeDetails field value if set, zero value otherwise.
func (o *TimeZoneDetailedXMLResponse) GetLoCodeDetails() TimezoneLocode {
	if o == nil || IsNil(o.LoCodeDetails) {
		var ret TimezoneLocode
		return ret
	}
	return *o.LoCodeDetails
}

// GetLoCodeDetailsOk returns a tuple with the LoCodeDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeZoneDetailedXMLResponse) GetLoCodeDetailsOk() (*TimezoneLocode, bool) {
	if o == nil || IsNil(o.LoCodeDetails) {
		return nil, false
	}
	return o.LoCodeDetails, true
}

// HasLoCodeDetails returns a boolean if a field has been set.
func (o *TimeZoneDetailedXMLResponse) HasLoCodeDetails() bool {
	if o != nil && !IsNil(o.LoCodeDetails) {
		return true
	}

	return false
}

// SetLoCodeDetails gets a reference to the given TimezoneLocode and assigns it to the LoCodeDetails field.
func (o *TimeZoneDetailedXMLResponse) SetLoCodeDetails(v TimezoneLocode) {
	o.LoCodeDetails = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *TimeZoneDetailedXMLResponse) GetLocation() TimezoneLocation {
	if o == nil || IsNil(o.Location) {
		var ret TimezoneLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeZoneDetailedXMLResponse) GetLocationOk() (*TimezoneLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *TimeZoneDetailedXMLResponse) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given TimezoneLocation and assigns it to the Location field.
func (o *TimeZoneDetailedXMLResponse) SetLocation(v TimezoneLocation) {
	o.Location = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *TimeZoneDetailedXMLResponse) GetTimeZone() TimezoneDetail {
	if o == nil || IsNil(o.TimeZone) {
		var ret TimezoneDetail
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeZoneDetailedXMLResponse) GetTimeZoneOk() (*TimezoneDetail, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *TimeZoneDetailedXMLResponse) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given TimezoneDetail and assigns it to the TimeZone field.
func (o *TimeZoneDetailedXMLResponse) SetTimeZone(v TimezoneDetail) {
	o.TimeZone = &v
}

func (o TimeZoneDetailedXMLResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeZoneDetailedXMLResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.AirportDetails) {
		toSerialize["airport_details"] = o.AirportDetails
	}
	if !IsNil(o.LoCodeDetails) {
		toSerialize["lo_code_details"] = o.LoCodeDetails
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.TimeZone) {
		toSerialize["time_zone"] = o.TimeZone
	}
	return toSerialize, nil
}

type NullableTimeZoneDetailedXMLResponse struct {
	value *TimeZoneDetailedXMLResponse
	isSet bool
}

func (v NullableTimeZoneDetailedXMLResponse) Get() *TimeZoneDetailedXMLResponse {
	return v.value
}

func (v *NullableTimeZoneDetailedXMLResponse) Set(val *TimeZoneDetailedXMLResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeZoneDetailedXMLResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeZoneDetailedXMLResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeZoneDetailedXMLResponse(val *TimeZoneDetailedXMLResponse) *NullableTimeZoneDetailedXMLResponse {
	return &NullableTimeZoneDetailedXMLResponse{value: val, isSet: true}
}

func (v NullableTimeZoneDetailedXMLResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeZoneDetailedXMLResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


