/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the UserAgentDataOperatingSystem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAgentDataOperatingSystem{}

// UserAgentDataOperatingSystem struct for UserAgentDataOperatingSystem
type UserAgentDataOperatingSystem struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Version *string `json:"version,omitempty"`
	VersionMajor *string `json:"version_major,omitempty"`
	Build *string `json:"build,omitempty"`
}

// NewUserAgentDataOperatingSystem instantiates a new UserAgentDataOperatingSystem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAgentDataOperatingSystem() *UserAgentDataOperatingSystem {
	this := UserAgentDataOperatingSystem{}
	return &this
}

// NewUserAgentDataOperatingSystemWithDefaults instantiates a new UserAgentDataOperatingSystem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAgentDataOperatingSystemWithDefaults() *UserAgentDataOperatingSystem {
	this := UserAgentDataOperatingSystem{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserAgentDataOperatingSystem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAgentDataOperatingSystem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserAgentDataOperatingSystem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserAgentDataOperatingSystem) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UserAgentDataOperatingSystem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAgentDataOperatingSystem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UserAgentDataOperatingSystem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UserAgentDataOperatingSystem) SetType(v string) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UserAgentDataOperatingSystem) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAgentDataOperatingSystem) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UserAgentDataOperatingSystem) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *UserAgentDataOperatingSystem) SetVersion(v string) {
	o.Version = &v
}

// GetVersionMajor returns the VersionMajor field value if set, zero value otherwise.
func (o *UserAgentDataOperatingSystem) GetVersionMajor() string {
	if o == nil || IsNil(o.VersionMajor) {
		var ret string
		return ret
	}
	return *o.VersionMajor
}

// GetVersionMajorOk returns a tuple with the VersionMajor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAgentDataOperatingSystem) GetVersionMajorOk() (*string, bool) {
	if o == nil || IsNil(o.VersionMajor) {
		return nil, false
	}
	return o.VersionMajor, true
}

// HasVersionMajor returns a boolean if a field has been set.
func (o *UserAgentDataOperatingSystem) HasVersionMajor() bool {
	if o != nil && !IsNil(o.VersionMajor) {
		return true
	}

	return false
}

// SetVersionMajor gets a reference to the given string and assigns it to the VersionMajor field.
func (o *UserAgentDataOperatingSystem) SetVersionMajor(v string) {
	o.VersionMajor = &v
}

// GetBuild returns the Build field value if set, zero value otherwise.
func (o *UserAgentDataOperatingSystem) GetBuild() string {
	if o == nil || IsNil(o.Build) {
		var ret string
		return ret
	}
	return *o.Build
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAgentDataOperatingSystem) GetBuildOk() (*string, bool) {
	if o == nil || IsNil(o.Build) {
		return nil, false
	}
	return o.Build, true
}

// HasBuild returns a boolean if a field has been set.
func (o *UserAgentDataOperatingSystem) HasBuild() bool {
	if o != nil && !IsNil(o.Build) {
		return true
	}

	return false
}

// SetBuild gets a reference to the given string and assigns it to the Build field.
func (o *UserAgentDataOperatingSystem) SetBuild(v string) {
	o.Build = &v
}

func (o UserAgentDataOperatingSystem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAgentDataOperatingSystem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.VersionMajor) {
		toSerialize["version_major"] = o.VersionMajor
	}
	if !IsNil(o.Build) {
		toSerialize["build"] = o.Build
	}
	return toSerialize, nil
}

type NullableUserAgentDataOperatingSystem struct {
	value *UserAgentDataOperatingSystem
	isSet bool
}

func (v NullableUserAgentDataOperatingSystem) Get() *UserAgentDataOperatingSystem {
	return v.value
}

func (v *NullableUserAgentDataOperatingSystem) Set(val *UserAgentDataOperatingSystem) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAgentDataOperatingSystem) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAgentDataOperatingSystem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAgentDataOperatingSystem(val *UserAgentDataOperatingSystem) *NullableUserAgentDataOperatingSystem {
	return &NullableUserAgentDataOperatingSystem{value: val, isSet: true}
}

func (v NullableUserAgentDataOperatingSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAgentDataOperatingSystem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


