/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the GeolocationXMLResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeolocationXMLResponse{}

// GeolocationXMLResponse struct for GeolocationXMLResponse
type GeolocationXMLResponse struct {
	Ip *string `json:"ip,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Location *Location `json:"location,omitempty"`
	CountryMetadata *CountryMetadata `json:"country_metadata,omitempty"`
	Network *Network `json:"network,omitempty"`
	Currency *Currency `json:"currency,omitempty"`
	Security *Security `json:"security,omitempty"`
	Abuse *Abuse `json:"abuse,omitempty"`
	TimeZone *TimeZone `json:"time_zone,omitempty"`
	UserAgent *UserAgentData `json:"user_agent,omitempty"`
}

// NewGeolocationXMLResponse instantiates a new GeolocationXMLResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeolocationXMLResponse() *GeolocationXMLResponse {
	this := GeolocationXMLResponse{}
	return &this
}

// NewGeolocationXMLResponseWithDefaults instantiates a new GeolocationXMLResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeolocationXMLResponseWithDefaults() *GeolocationXMLResponse {
	this := GeolocationXMLResponse{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *GeolocationXMLResponse) SetIp(v string) {
	o.Ip = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *GeolocationXMLResponse) SetHostname(v string) {
	o.Hostname = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *GeolocationXMLResponse) SetDomain(v string) {
	o.Domain = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetLocation() Location {
	if o == nil || IsNil(o.Location) {
		var ret Location
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetLocationOk() (*Location, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given Location and assigns it to the Location field.
func (o *GeolocationXMLResponse) SetLocation(v Location) {
	o.Location = &v
}

// GetCountryMetadata returns the CountryMetadata field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetCountryMetadata() CountryMetadata {
	if o == nil || IsNil(o.CountryMetadata) {
		var ret CountryMetadata
		return ret
	}
	return *o.CountryMetadata
}

// GetCountryMetadataOk returns a tuple with the CountryMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetCountryMetadataOk() (*CountryMetadata, bool) {
	if o == nil || IsNil(o.CountryMetadata) {
		return nil, false
	}
	return o.CountryMetadata, true
}

// HasCountryMetadata returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasCountryMetadata() bool {
	if o != nil && !IsNil(o.CountryMetadata) {
		return true
	}

	return false
}

// SetCountryMetadata gets a reference to the given CountryMetadata and assigns it to the CountryMetadata field.
func (o *GeolocationXMLResponse) SetCountryMetadata(v CountryMetadata) {
	o.CountryMetadata = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetNetwork() Network {
	if o == nil || IsNil(o.Network) {
		var ret Network
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetNetworkOk() (*Network, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given Network and assigns it to the Network field.
func (o *GeolocationXMLResponse) SetNetwork(v Network) {
	o.Network = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *GeolocationXMLResponse) SetCurrency(v Currency) {
	o.Currency = &v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetSecurity() Security {
	if o == nil || IsNil(o.Security) {
		var ret Security
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetSecurityOk() (*Security, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given Security and assigns it to the Security field.
func (o *GeolocationXMLResponse) SetSecurity(v Security) {
	o.Security = &v
}

// GetAbuse returns the Abuse field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetAbuse() Abuse {
	if o == nil || IsNil(o.Abuse) {
		var ret Abuse
		return ret
	}
	return *o.Abuse
}

// GetAbuseOk returns a tuple with the Abuse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetAbuseOk() (*Abuse, bool) {
	if o == nil || IsNil(o.Abuse) {
		return nil, false
	}
	return o.Abuse, true
}

// HasAbuse returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasAbuse() bool {
	if o != nil && !IsNil(o.Abuse) {
		return true
	}

	return false
}

// SetAbuse gets a reference to the given Abuse and assigns it to the Abuse field.
func (o *GeolocationXMLResponse) SetAbuse(v Abuse) {
	o.Abuse = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetTimeZone() TimeZone {
	if o == nil || IsNil(o.TimeZone) {
		var ret TimeZone
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetTimeZoneOk() (*TimeZone, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given TimeZone and assigns it to the TimeZone field.
func (o *GeolocationXMLResponse) SetTimeZone(v TimeZone) {
	o.TimeZone = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *GeolocationXMLResponse) GetUserAgent() UserAgentData {
	if o == nil || IsNil(o.UserAgent) {
		var ret UserAgentData
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeolocationXMLResponse) GetUserAgentOk() (*UserAgentData, bool) {
	if o == nil || IsNil(o.UserAgent) {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *GeolocationXMLResponse) HasUserAgent() bool {
	if o != nil && !IsNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given UserAgentData and assigns it to the UserAgent field.
func (o *GeolocationXMLResponse) SetUserAgent(v UserAgentData) {
	o.UserAgent = &v
}

func (o GeolocationXMLResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeolocationXMLResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.CountryMetadata) {
		toSerialize["country_metadata"] = o.CountryMetadata
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	if !IsNil(o.Abuse) {
		toSerialize["abuse"] = o.Abuse
	}
	if !IsNil(o.TimeZone) {
		toSerialize["time_zone"] = o.TimeZone
	}
	if !IsNil(o.UserAgent) {
		toSerialize["user_agent"] = o.UserAgent
	}
	return toSerialize, nil
}

type NullableGeolocationXMLResponse struct {
	value *GeolocationXMLResponse
	isSet bool
}

func (v NullableGeolocationXMLResponse) Get() *GeolocationXMLResponse {
	return v.value
}

func (v *NullableGeolocationXMLResponse) Set(val *GeolocationXMLResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGeolocationXMLResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGeolocationXMLResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeolocationXMLResponse(val *GeolocationXMLResponse) *NullableGeolocationXMLResponse {
	return &NullableGeolocationXMLResponse{value: val, isSet: true}
}

func (v NullableGeolocationXMLResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeolocationXMLResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


