/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the NetworkAsn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkAsn{}

// NetworkAsn struct for NetworkAsn
type NetworkAsn struct {
	AsNumber *string `json:"as_number,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Country *string `json:"country,omitempty"`
	AsnName *string `json:"asn_name,omitempty"`
	Type *string `json:"type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	DateAllocated *string `json:"date_allocated,omitempty"`
	AllocationStatus *string `json:"allocation_status,omitempty"`
	NumOfIpv4Routes *string `json:"num_of_ipv4_routes,omitempty"`
	NumOfIpv6Routes *string `json:"num_of_ipv6_routes,omitempty"`
	Rir *string `json:"rir,omitempty"`
}

// NewNetworkAsn instantiates a new NetworkAsn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkAsn() *NetworkAsn {
	this := NetworkAsn{}
	return &this
}

// NewNetworkAsnWithDefaults instantiates a new NetworkAsn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkAsnWithDefaults() *NetworkAsn {
	this := NetworkAsn{}
	return &this
}

// GetAsNumber returns the AsNumber field value if set, zero value otherwise.
func (o *NetworkAsn) GetAsNumber() string {
	if o == nil || IsNil(o.AsNumber) {
		var ret string
		return ret
	}
	return *o.AsNumber
}

// GetAsNumberOk returns a tuple with the AsNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetAsNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AsNumber) {
		return nil, false
	}
	return o.AsNumber, true
}

// HasAsNumber returns a boolean if a field has been set.
func (o *NetworkAsn) HasAsNumber() bool {
	if o != nil && !IsNil(o.AsNumber) {
		return true
	}

	return false
}

// SetAsNumber gets a reference to the given string and assigns it to the AsNumber field.
func (o *NetworkAsn) SetAsNumber(v string) {
	o.AsNumber = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *NetworkAsn) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *NetworkAsn) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *NetworkAsn) SetOrganization(v string) {
	o.Organization = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *NetworkAsn) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *NetworkAsn) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *NetworkAsn) SetCountry(v string) {
	o.Country = &v
}

// GetAsnName returns the AsnName field value if set, zero value otherwise.
func (o *NetworkAsn) GetAsnName() string {
	if o == nil || IsNil(o.AsnName) {
		var ret string
		return ret
	}
	return *o.AsnName
}

// GetAsnNameOk returns a tuple with the AsnName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetAsnNameOk() (*string, bool) {
	if o == nil || IsNil(o.AsnName) {
		return nil, false
	}
	return o.AsnName, true
}

// HasAsnName returns a boolean if a field has been set.
func (o *NetworkAsn) HasAsnName() bool {
	if o != nil && !IsNil(o.AsnName) {
		return true
	}

	return false
}

// SetAsnName gets a reference to the given string and assigns it to the AsnName field.
func (o *NetworkAsn) SetAsnName(v string) {
	o.AsnName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NetworkAsn) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NetworkAsn) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NetworkAsn) SetType(v string) {
	o.Type = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *NetworkAsn) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *NetworkAsn) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *NetworkAsn) SetDomain(v string) {
	o.Domain = &v
}

// GetDateAllocated returns the DateAllocated field value if set, zero value otherwise.
func (o *NetworkAsn) GetDateAllocated() string {
	if o == nil || IsNil(o.DateAllocated) {
		var ret string
		return ret
	}
	return *o.DateAllocated
}

// GetDateAllocatedOk returns a tuple with the DateAllocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetDateAllocatedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAllocated) {
		return nil, false
	}
	return o.DateAllocated, true
}

// HasDateAllocated returns a boolean if a field has been set.
func (o *NetworkAsn) HasDateAllocated() bool {
	if o != nil && !IsNil(o.DateAllocated) {
		return true
	}

	return false
}

// SetDateAllocated gets a reference to the given string and assigns it to the DateAllocated field.
func (o *NetworkAsn) SetDateAllocated(v string) {
	o.DateAllocated = &v
}

// GetAllocationStatus returns the AllocationStatus field value if set, zero value otherwise.
func (o *NetworkAsn) GetAllocationStatus() string {
	if o == nil || IsNil(o.AllocationStatus) {
		var ret string
		return ret
	}
	return *o.AllocationStatus
}

// GetAllocationStatusOk returns a tuple with the AllocationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetAllocationStatusOk() (*string, bool) {
	if o == nil || IsNil(o.AllocationStatus) {
		return nil, false
	}
	return o.AllocationStatus, true
}

// HasAllocationStatus returns a boolean if a field has been set.
func (o *NetworkAsn) HasAllocationStatus() bool {
	if o != nil && !IsNil(o.AllocationStatus) {
		return true
	}

	return false
}

// SetAllocationStatus gets a reference to the given string and assigns it to the AllocationStatus field.
func (o *NetworkAsn) SetAllocationStatus(v string) {
	o.AllocationStatus = &v
}

// GetNumOfIpv4Routes returns the NumOfIpv4Routes field value if set, zero value otherwise.
func (o *NetworkAsn) GetNumOfIpv4Routes() string {
	if o == nil || IsNil(o.NumOfIpv4Routes) {
		var ret string
		return ret
	}
	return *o.NumOfIpv4Routes
}

// GetNumOfIpv4RoutesOk returns a tuple with the NumOfIpv4Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetNumOfIpv4RoutesOk() (*string, bool) {
	if o == nil || IsNil(o.NumOfIpv4Routes) {
		return nil, false
	}
	return o.NumOfIpv4Routes, true
}

// HasNumOfIpv4Routes returns a boolean if a field has been set.
func (o *NetworkAsn) HasNumOfIpv4Routes() bool {
	if o != nil && !IsNil(o.NumOfIpv4Routes) {
		return true
	}

	return false
}

// SetNumOfIpv4Routes gets a reference to the given string and assigns it to the NumOfIpv4Routes field.
func (o *NetworkAsn) SetNumOfIpv4Routes(v string) {
	o.NumOfIpv4Routes = &v
}

// GetNumOfIpv6Routes returns the NumOfIpv6Routes field value if set, zero value otherwise.
func (o *NetworkAsn) GetNumOfIpv6Routes() string {
	if o == nil || IsNil(o.NumOfIpv6Routes) {
		var ret string
		return ret
	}
	return *o.NumOfIpv6Routes
}

// GetNumOfIpv6RoutesOk returns a tuple with the NumOfIpv6Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetNumOfIpv6RoutesOk() (*string, bool) {
	if o == nil || IsNil(o.NumOfIpv6Routes) {
		return nil, false
	}
	return o.NumOfIpv6Routes, true
}

// HasNumOfIpv6Routes returns a boolean if a field has been set.
func (o *NetworkAsn) HasNumOfIpv6Routes() bool {
	if o != nil && !IsNil(o.NumOfIpv6Routes) {
		return true
	}

	return false
}

// SetNumOfIpv6Routes gets a reference to the given string and assigns it to the NumOfIpv6Routes field.
func (o *NetworkAsn) SetNumOfIpv6Routes(v string) {
	o.NumOfIpv6Routes = &v
}

// GetRir returns the Rir field value if set, zero value otherwise.
func (o *NetworkAsn) GetRir() string {
	if o == nil || IsNil(o.Rir) {
		var ret string
		return ret
	}
	return *o.Rir
}

// GetRirOk returns a tuple with the Rir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkAsn) GetRirOk() (*string, bool) {
	if o == nil || IsNil(o.Rir) {
		return nil, false
	}
	return o.Rir, true
}

// HasRir returns a boolean if a field has been set.
func (o *NetworkAsn) HasRir() bool {
	if o != nil && !IsNil(o.Rir) {
		return true
	}

	return false
}

// SetRir gets a reference to the given string and assigns it to the Rir field.
func (o *NetworkAsn) SetRir(v string) {
	o.Rir = &v
}

func (o NetworkAsn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkAsn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AsNumber) {
		toSerialize["as_number"] = o.AsNumber
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.AsnName) {
		toSerialize["asn_name"] = o.AsnName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.DateAllocated) {
		toSerialize["date_allocated"] = o.DateAllocated
	}
	if !IsNil(o.AllocationStatus) {
		toSerialize["allocation_status"] = o.AllocationStatus
	}
	if !IsNil(o.NumOfIpv4Routes) {
		toSerialize["num_of_ipv4_routes"] = o.NumOfIpv4Routes
	}
	if !IsNil(o.NumOfIpv6Routes) {
		toSerialize["num_of_ipv6_routes"] = o.NumOfIpv6Routes
	}
	if !IsNil(o.Rir) {
		toSerialize["rir"] = o.Rir
	}
	return toSerialize, nil
}

type NullableNetworkAsn struct {
	value *NetworkAsn
	isSet bool
}

func (v NullableNetworkAsn) Get() *NetworkAsn {
	return v.value
}

func (v *NullableNetworkAsn) Set(val *NetworkAsn) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkAsn) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkAsn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkAsn(val *NetworkAsn) *NullableNetworkAsn {
	return &NullableNetworkAsn{value: val, isSet: true}
}

func (v NullableNetworkAsn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkAsn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


