/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the Location type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Location{}

// Location struct for Location
type Location struct {
	ContinentCode *string `json:"continent_code,omitempty"`
	ContinentName *string `json:"continent_name,omitempty"`
	CountryCode2 *string `json:"country_code2,omitempty"`
	CountryCode3 *string `json:"country_code3,omitempty"`
	CountryName *string `json:"country_name,omitempty"`
	CountryNameOfficial *string `json:"country_name_official,omitempty"`
	CountryCapital *string `json:"country_capital,omitempty"`
	StateProv *string `json:"state_prov,omitempty"`
	StateCode *string `json:"state_code,omitempty"`
	District *string `json:"district,omitempty"`
	City *string `json:"city,omitempty"`
	Zipcode *string `json:"zipcode,omitempty"`
	Latitude *string `json:"latitude,omitempty"`
	Longitude *string `json:"longitude,omitempty"`
	IsEu *bool `json:"is_eu,omitempty"`
	CountryFlag *string `json:"country_flag,omitempty"`
	GeonameId *string `json:"geoname_id,omitempty"`
	CountryEmoji *string `json:"country_emoji,omitempty"`
	AccuracyRadius *string `json:"accuracy_radius,omitempty"`
	Locality *string `json:"locality,omitempty"`
	DmaCode *string `json:"dma_code,omitempty"`
}

// NewLocation instantiates a new Location object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocation() *Location {
	this := Location{}
	return &this
}

// NewLocationWithDefaults instantiates a new Location object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationWithDefaults() *Location {
	this := Location{}
	return &this
}

// GetContinentCode returns the ContinentCode field value if set, zero value otherwise.
func (o *Location) GetContinentCode() string {
	if o == nil || IsNil(o.ContinentCode) {
		var ret string
		return ret
	}
	return *o.ContinentCode
}

// GetContinentCodeOk returns a tuple with the ContinentCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetContinentCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ContinentCode) {
		return nil, false
	}
	return o.ContinentCode, true
}

// HasContinentCode returns a boolean if a field has been set.
func (o *Location) HasContinentCode() bool {
	if o != nil && !IsNil(o.ContinentCode) {
		return true
	}

	return false
}

// SetContinentCode gets a reference to the given string and assigns it to the ContinentCode field.
func (o *Location) SetContinentCode(v string) {
	o.ContinentCode = &v
}

// GetContinentName returns the ContinentName field value if set, zero value otherwise.
func (o *Location) GetContinentName() string {
	if o == nil || IsNil(o.ContinentName) {
		var ret string
		return ret
	}
	return *o.ContinentName
}

// GetContinentNameOk returns a tuple with the ContinentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetContinentNameOk() (*string, bool) {
	if o == nil || IsNil(o.ContinentName) {
		return nil, false
	}
	return o.ContinentName, true
}

// HasContinentName returns a boolean if a field has been set.
func (o *Location) HasContinentName() bool {
	if o != nil && !IsNil(o.ContinentName) {
		return true
	}

	return false
}

// SetContinentName gets a reference to the given string and assigns it to the ContinentName field.
func (o *Location) SetContinentName(v string) {
	o.ContinentName = &v
}

// GetCountryCode2 returns the CountryCode2 field value if set, zero value otherwise.
func (o *Location) GetCountryCode2() string {
	if o == nil || IsNil(o.CountryCode2) {
		var ret string
		return ret
	}
	return *o.CountryCode2
}

// GetCountryCode2Ok returns a tuple with the CountryCode2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryCode2Ok() (*string, bool) {
	if o == nil || IsNil(o.CountryCode2) {
		return nil, false
	}
	return o.CountryCode2, true
}

// HasCountryCode2 returns a boolean if a field has been set.
func (o *Location) HasCountryCode2() bool {
	if o != nil && !IsNil(o.CountryCode2) {
		return true
	}

	return false
}

// SetCountryCode2 gets a reference to the given string and assigns it to the CountryCode2 field.
func (o *Location) SetCountryCode2(v string) {
	o.CountryCode2 = &v
}

// GetCountryCode3 returns the CountryCode3 field value if set, zero value otherwise.
func (o *Location) GetCountryCode3() string {
	if o == nil || IsNil(o.CountryCode3) {
		var ret string
		return ret
	}
	return *o.CountryCode3
}

// GetCountryCode3Ok returns a tuple with the CountryCode3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryCode3Ok() (*string, bool) {
	if o == nil || IsNil(o.CountryCode3) {
		return nil, false
	}
	return o.CountryCode3, true
}

// HasCountryCode3 returns a boolean if a field has been set.
func (o *Location) HasCountryCode3() bool {
	if o != nil && !IsNil(o.CountryCode3) {
		return true
	}

	return false
}

// SetCountryCode3 gets a reference to the given string and assigns it to the CountryCode3 field.
func (o *Location) SetCountryCode3(v string) {
	o.CountryCode3 = &v
}

// GetCountryName returns the CountryName field value if set, zero value otherwise.
func (o *Location) GetCountryName() string {
	if o == nil || IsNil(o.CountryName) {
		var ret string
		return ret
	}
	return *o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryNameOk() (*string, bool) {
	if o == nil || IsNil(o.CountryName) {
		return nil, false
	}
	return o.CountryName, true
}

// HasCountryName returns a boolean if a field has been set.
func (o *Location) HasCountryName() bool {
	if o != nil && !IsNil(o.CountryName) {
		return true
	}

	return false
}

// SetCountryName gets a reference to the given string and assigns it to the CountryName field.
func (o *Location) SetCountryName(v string) {
	o.CountryName = &v
}

// GetCountryNameOfficial returns the CountryNameOfficial field value if set, zero value otherwise.
func (o *Location) GetCountryNameOfficial() string {
	if o == nil || IsNil(o.CountryNameOfficial) {
		var ret string
		return ret
	}
	return *o.CountryNameOfficial
}

// GetCountryNameOfficialOk returns a tuple with the CountryNameOfficial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryNameOfficialOk() (*string, bool) {
	if o == nil || IsNil(o.CountryNameOfficial) {
		return nil, false
	}
	return o.CountryNameOfficial, true
}

// HasCountryNameOfficial returns a boolean if a field has been set.
func (o *Location) HasCountryNameOfficial() bool {
	if o != nil && !IsNil(o.CountryNameOfficial) {
		return true
	}

	return false
}

// SetCountryNameOfficial gets a reference to the given string and assigns it to the CountryNameOfficial field.
func (o *Location) SetCountryNameOfficial(v string) {
	o.CountryNameOfficial = &v
}

// GetCountryCapital returns the CountryCapital field value if set, zero value otherwise.
func (o *Location) GetCountryCapital() string {
	if o == nil || IsNil(o.CountryCapital) {
		var ret string
		return ret
	}
	return *o.CountryCapital
}

// GetCountryCapitalOk returns a tuple with the CountryCapital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryCapitalOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCapital) {
		return nil, false
	}
	return o.CountryCapital, true
}

// HasCountryCapital returns a boolean if a field has been set.
func (o *Location) HasCountryCapital() bool {
	if o != nil && !IsNil(o.CountryCapital) {
		return true
	}

	return false
}

// SetCountryCapital gets a reference to the given string and assigns it to the CountryCapital field.
func (o *Location) SetCountryCapital(v string) {
	o.CountryCapital = &v
}

// GetStateProv returns the StateProv field value if set, zero value otherwise.
func (o *Location) GetStateProv() string {
	if o == nil || IsNil(o.StateProv) {
		var ret string
		return ret
	}
	return *o.StateProv
}

// GetStateProvOk returns a tuple with the StateProv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetStateProvOk() (*string, bool) {
	if o == nil || IsNil(o.StateProv) {
		return nil, false
	}
	return o.StateProv, true
}

// HasStateProv returns a boolean if a field has been set.
func (o *Location) HasStateProv() bool {
	if o != nil && !IsNil(o.StateProv) {
		return true
	}

	return false
}

// SetStateProv gets a reference to the given string and assigns it to the StateProv field.
func (o *Location) SetStateProv(v string) {
	o.StateProv = &v
}

// GetStateCode returns the StateCode field value if set, zero value otherwise.
func (o *Location) GetStateCode() string {
	if o == nil || IsNil(o.StateCode) {
		var ret string
		return ret
	}
	return *o.StateCode
}

// GetStateCodeOk returns a tuple with the StateCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetStateCodeOk() (*string, bool) {
	if o == nil || IsNil(o.StateCode) {
		return nil, false
	}
	return o.StateCode, true
}

// HasStateCode returns a boolean if a field has been set.
func (o *Location) HasStateCode() bool {
	if o != nil && !IsNil(o.StateCode) {
		return true
	}

	return false
}

// SetStateCode gets a reference to the given string and assigns it to the StateCode field.
func (o *Location) SetStateCode(v string) {
	o.StateCode = &v
}

// GetDistrict returns the District field value if set, zero value otherwise.
func (o *Location) GetDistrict() string {
	if o == nil || IsNil(o.District) {
		var ret string
		return ret
	}
	return *o.District
}

// GetDistrictOk returns a tuple with the District field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetDistrictOk() (*string, bool) {
	if o == nil || IsNil(o.District) {
		return nil, false
	}
	return o.District, true
}

// HasDistrict returns a boolean if a field has been set.
func (o *Location) HasDistrict() bool {
	if o != nil && !IsNil(o.District) {
		return true
	}

	return false
}

// SetDistrict gets a reference to the given string and assigns it to the District field.
func (o *Location) SetDistrict(v string) {
	o.District = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *Location) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *Location) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *Location) SetCity(v string) {
	o.City = &v
}

// GetZipcode returns the Zipcode field value if set, zero value otherwise.
func (o *Location) GetZipcode() string {
	if o == nil || IsNil(o.Zipcode) {
		var ret string
		return ret
	}
	return *o.Zipcode
}

// GetZipcodeOk returns a tuple with the Zipcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetZipcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Zipcode) {
		return nil, false
	}
	return o.Zipcode, true
}

// HasZipcode returns a boolean if a field has been set.
func (o *Location) HasZipcode() bool {
	if o != nil && !IsNil(o.Zipcode) {
		return true
	}

	return false
}

// SetZipcode gets a reference to the given string and assigns it to the Zipcode field.
func (o *Location) SetZipcode(v string) {
	o.Zipcode = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *Location) GetLatitude() string {
	if o == nil || IsNil(o.Latitude) {
		var ret string
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetLatitudeOk() (*string, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *Location) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given string and assigns it to the Latitude field.
func (o *Location) SetLatitude(v string) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *Location) GetLongitude() string {
	if o == nil || IsNil(o.Longitude) {
		var ret string
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetLongitudeOk() (*string, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *Location) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given string and assigns it to the Longitude field.
func (o *Location) SetLongitude(v string) {
	o.Longitude = &v
}

// GetIsEu returns the IsEu field value if set, zero value otherwise.
func (o *Location) GetIsEu() bool {
	if o == nil || IsNil(o.IsEu) {
		var ret bool
		return ret
	}
	return *o.IsEu
}

// GetIsEuOk returns a tuple with the IsEu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetIsEuOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEu) {
		return nil, false
	}
	return o.IsEu, true
}

// HasIsEu returns a boolean if a field has been set.
func (o *Location) HasIsEu() bool {
	if o != nil && !IsNil(o.IsEu) {
		return true
	}

	return false
}

// SetIsEu gets a reference to the given bool and assigns it to the IsEu field.
func (o *Location) SetIsEu(v bool) {
	o.IsEu = &v
}

// GetCountryFlag returns the CountryFlag field value if set, zero value otherwise.
func (o *Location) GetCountryFlag() string {
	if o == nil || IsNil(o.CountryFlag) {
		var ret string
		return ret
	}
	return *o.CountryFlag
}

// GetCountryFlagOk returns a tuple with the CountryFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryFlagOk() (*string, bool) {
	if o == nil || IsNil(o.CountryFlag) {
		return nil, false
	}
	return o.CountryFlag, true
}

// HasCountryFlag returns a boolean if a field has been set.
func (o *Location) HasCountryFlag() bool {
	if o != nil && !IsNil(o.CountryFlag) {
		return true
	}

	return false
}

// SetCountryFlag gets a reference to the given string and assigns it to the CountryFlag field.
func (o *Location) SetCountryFlag(v string) {
	o.CountryFlag = &v
}

// GetGeonameId returns the GeonameId field value if set, zero value otherwise.
func (o *Location) GetGeonameId() string {
	if o == nil || IsNil(o.GeonameId) {
		var ret string
		return ret
	}
	return *o.GeonameId
}

// GetGeonameIdOk returns a tuple with the GeonameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetGeonameIdOk() (*string, bool) {
	if o == nil || IsNil(o.GeonameId) {
		return nil, false
	}
	return o.GeonameId, true
}

// HasGeonameId returns a boolean if a field has been set.
func (o *Location) HasGeonameId() bool {
	if o != nil && !IsNil(o.GeonameId) {
		return true
	}

	return false
}

// SetGeonameId gets a reference to the given string and assigns it to the GeonameId field.
func (o *Location) SetGeonameId(v string) {
	o.GeonameId = &v
}

// GetCountryEmoji returns the CountryEmoji field value if set, zero value otherwise.
func (o *Location) GetCountryEmoji() string {
	if o == nil || IsNil(o.CountryEmoji) {
		var ret string
		return ret
	}
	return *o.CountryEmoji
}

// GetCountryEmojiOk returns a tuple with the CountryEmoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetCountryEmojiOk() (*string, bool) {
	if o == nil || IsNil(o.CountryEmoji) {
		return nil, false
	}
	return o.CountryEmoji, true
}

// HasCountryEmoji returns a boolean if a field has been set.
func (o *Location) HasCountryEmoji() bool {
	if o != nil && !IsNil(o.CountryEmoji) {
		return true
	}

	return false
}

// SetCountryEmoji gets a reference to the given string and assigns it to the CountryEmoji field.
func (o *Location) SetCountryEmoji(v string) {
	o.CountryEmoji = &v
}

// GetAccuracyRadius returns the AccuracyRadius field value if set, zero value otherwise.
func (o *Location) GetAccuracyRadius() string {
	if o == nil || IsNil(o.AccuracyRadius) {
		var ret string
		return ret
	}
	return *o.AccuracyRadius
}

// GetAccuracyRadiusOk returns a tuple with the AccuracyRadius field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetAccuracyRadiusOk() (*string, bool) {
	if o == nil || IsNil(o.AccuracyRadius) {
		return nil, false
	}
	return o.AccuracyRadius, true
}

// HasAccuracyRadius returns a boolean if a field has been set.
func (o *Location) HasAccuracyRadius() bool {
	if o != nil && !IsNil(o.AccuracyRadius) {
		return true
	}

	return false
}

// SetAccuracyRadius gets a reference to the given string and assigns it to the AccuracyRadius field.
func (o *Location) SetAccuracyRadius(v string) {
	o.AccuracyRadius = &v
}

// GetLocality returns the Locality field value if set, zero value otherwise.
func (o *Location) GetLocality() string {
	if o == nil || IsNil(o.Locality) {
		var ret string
		return ret
	}
	return *o.Locality
}

// GetLocalityOk returns a tuple with the Locality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetLocalityOk() (*string, bool) {
	if o == nil || IsNil(o.Locality) {
		return nil, false
	}
	return o.Locality, true
}

// HasLocality returns a boolean if a field has been set.
func (o *Location) HasLocality() bool {
	if o != nil && !IsNil(o.Locality) {
		return true
	}

	return false
}

// SetLocality gets a reference to the given string and assigns it to the Locality field.
func (o *Location) SetLocality(v string) {
	o.Locality = &v
}

// GetDmaCode returns the DmaCode field value if set, zero value otherwise.
func (o *Location) GetDmaCode() string {
	if o == nil || IsNil(o.DmaCode) {
		var ret string
		return ret
	}
	return *o.DmaCode
}

// GetDmaCodeOk returns a tuple with the DmaCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Location) GetDmaCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DmaCode) {
		return nil, false
	}
	return o.DmaCode, true
}

// HasDmaCode returns a boolean if a field has been set.
func (o *Location) HasDmaCode() bool {
	if o != nil && !IsNil(o.DmaCode) {
		return true
	}

	return false
}

// SetDmaCode gets a reference to the given string and assigns it to the DmaCode field.
func (o *Location) SetDmaCode(v string) {
	o.DmaCode = &v
}

func (o Location) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Location) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContinentCode) {
		toSerialize["continent_code"] = o.ContinentCode
	}
	if !IsNil(o.ContinentName) {
		toSerialize["continent_name"] = o.ContinentName
	}
	if !IsNil(o.CountryCode2) {
		toSerialize["country_code2"] = o.CountryCode2
	}
	if !IsNil(o.CountryCode3) {
		toSerialize["country_code3"] = o.CountryCode3
	}
	if !IsNil(o.CountryName) {
		toSerialize["country_name"] = o.CountryName
	}
	if !IsNil(o.CountryNameOfficial) {
		toSerialize["country_name_official"] = o.CountryNameOfficial
	}
	if !IsNil(o.CountryCapital) {
		toSerialize["country_capital"] = o.CountryCapital
	}
	if !IsNil(o.StateProv) {
		toSerialize["state_prov"] = o.StateProv
	}
	if !IsNil(o.StateCode) {
		toSerialize["state_code"] = o.StateCode
	}
	if !IsNil(o.District) {
		toSerialize["district"] = o.District
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.Zipcode) {
		toSerialize["zipcode"] = o.Zipcode
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.IsEu) {
		toSerialize["is_eu"] = o.IsEu
	}
	if !IsNil(o.CountryFlag) {
		toSerialize["country_flag"] = o.CountryFlag
	}
	if !IsNil(o.GeonameId) {
		toSerialize["geoname_id"] = o.GeonameId
	}
	if !IsNil(o.CountryEmoji) {
		toSerialize["country_emoji"] = o.CountryEmoji
	}
	if !IsNil(o.AccuracyRadius) {
		toSerialize["accuracy_radius"] = o.AccuracyRadius
	}
	if !IsNil(o.Locality) {
		toSerialize["locality"] = o.Locality
	}
	if !IsNil(o.DmaCode) {
		toSerialize["dma_code"] = o.DmaCode
	}
	return toSerialize, nil
}

type NullableLocation struct {
	value *Location
	isSet bool
}

func (v NullableLocation) Get() *Location {
	return v.value
}

func (v *NullableLocation) Set(val *Location) {
	v.value = val
	v.isSet = true
}

func (v NullableLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocation(val *Location) *NullableLocation {
	return &NullableLocation{value: val, isSet: true}
}

func (v NullableLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


