/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the GetBulkIpGeolocationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBulkIpGeolocationRequest{}

// GetBulkIpGeolocationRequest struct for GetBulkIpGeolocationRequest
type GetBulkIpGeolocationRequest struct {
	Ips []string `json:"ips,omitempty"`
}

// NewGetBulkIpGeolocationRequest instantiates a new GetBulkIpGeolocationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBulkIpGeolocationRequest() *GetBulkIpGeolocationRequest {
	this := GetBulkIpGeolocationRequest{}
	return &this
}

// NewGetBulkIpGeolocationRequestWithDefaults instantiates a new GetBulkIpGeolocationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBulkIpGeolocationRequestWithDefaults() *GetBulkIpGeolocationRequest {
	this := GetBulkIpGeolocationRequest{}
	return &this
}

// GetIps returns the Ips field value if set, zero value otherwise.
func (o *GetBulkIpGeolocationRequest) GetIps() []string {
	if o == nil || IsNil(o.Ips) {
		var ret []string
		return ret
	}
	return o.Ips
}

// GetIpsOk returns a tuple with the Ips field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBulkIpGeolocationRequest) GetIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ips) {
		return nil, false
	}
	return o.Ips, true
}

// HasIps returns a boolean if a field has been set.
func (o *GetBulkIpGeolocationRequest) HasIps() bool {
	if o != nil && !IsNil(o.Ips) {
		return true
	}

	return false
}

// SetIps gets a reference to the given []string and assigns it to the Ips field.
func (o *GetBulkIpGeolocationRequest) SetIps(v []string) {
	o.Ips = v
}

func (o GetBulkIpGeolocationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBulkIpGeolocationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ips) {
		toSerialize["ips"] = o.Ips
	}
	return toSerialize, nil
}

type NullableGetBulkIpGeolocationRequest struct {
	value *GetBulkIpGeolocationRequest
	isSet bool
}

func (v NullableGetBulkIpGeolocationRequest) Get() *GetBulkIpGeolocationRequest {
	return v.value
}

func (v *NullableGetBulkIpGeolocationRequest) Set(val *GetBulkIpGeolocationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBulkIpGeolocationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBulkIpGeolocationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBulkIpGeolocationRequest(val *GetBulkIpGeolocationRequest) *NullableGetBulkIpGeolocationRequest {
	return &NullableGetBulkIpGeolocationRequest{value: val, isSet: true}
}

func (v NullableGetBulkIpGeolocationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBulkIpGeolocationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


