/*
IPGeolocation.io - IP intelligence products

Ipgeolocation provides a set of APIs to make ip based decisions.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipgeolocationsdk

import (
	"encoding/json"
)

// checks if the ErrorXMLResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorXMLResponse{}

// ErrorXMLResponse struct for ErrorXMLResponse
type ErrorXMLResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewErrorXMLResponse instantiates a new ErrorXMLResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorXMLResponse() *ErrorXMLResponse {
	this := ErrorXMLResponse{}
	return &this
}

// NewErrorXMLResponseWithDefaults instantiates a new ErrorXMLResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorXMLResponseWithDefaults() *ErrorXMLResponse {
	this := ErrorXMLResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrorXMLResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorXMLResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrorXMLResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ErrorXMLResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ErrorXMLResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorXMLResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableErrorXMLResponse struct {
	value *ErrorXMLResponse
	isSet bool
}

func (v NullableErrorXMLResponse) Get() *ErrorXMLResponse {
	return v.value
}

func (v *NullableErrorXMLResponse) Set(val *ErrorXMLResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorXMLResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorXMLResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorXMLResponse(val *ErrorXMLResponse) *NullableErrorXMLResponse {
	return &NullableErrorXMLResponse{value: val, isSet: true}
}

func (v NullableErrorXMLResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorXMLResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


